packages:
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  argon2: false
  better-sqlite3: false
  esbuild: false
  sqlite3: false
onlyBuiltDependencies:
  - argon2
  - better-sqlite3
  - esbuild
  - sqlite3
