/**
 * Maps DST numeric IDs to human-readable names (from defineAttribute.h).
 * Used by the admin panel to label item effects and set bonuses.
 */
export const DST_NAMES: Record<number, string> = {
  0: "None",
  1: "STR",
  2: "DEX",
  3: "INT",
  4: "STA",
  5: "Yo-Yo DMG",
  6: "Bow DMG",
  7: "Attack Range",
  8: "Block Range",
  9: "Critical Chance",
  10: "Bleeding",
  11: "Speed",
  12: "ATK Min",
  13: "ATK Max",
  14: "Block Melee",
  15: "Mastery Earth",
  16: "Stop Movement",
  17: "Mastery Fire",
  18: "Mastery Water",
  19: "Mastery Electricity",
  20: "Mastery Wind",
  21: "Knuckle DMG",
  22: "PVP DMG Rate",
  24: "Attack Speed",
  25: "Sword DMG",
  26: "DEF",
  27: "Resist Magic",
  28: "Resist Electricity",
  29: "Reflect DMG",
  30: "Resist Fire",
  31: "Resist Wind",
  32: "Resist Water",
  33: "Resist Earth",
  34: "Axe DMG",
  35: "HP Max",
  36: "MP Max",
  37: "FP Max",
  38: "HP",
  39: "MP",
  40: "FP",
  41: "HP Recovery",
  42: "MP Recovery",
  43: "FP Recovery",
  44: "Kill HP",
  45: "Kill MP",
  46: "Kill FP",
  47: "Hit Rate",
  49: "Clear Buff",
  50: "Steal HP (Imm)",
  51: "ATK Speed Rate",
  52: "HP Max Rate",
  53: "MP Max Rate",
  54: "FP Max Rate",
  55: "Element ATK",
  56: "Steal HP",
  57: "Chance Stun",
  58: "Auto HP",
  59: "Chance Dark",
  60: "Chance Poison",
  61: "Immunity",
  62: "Add Magic",
  63: "ATK Power",
  64: "Char State",
  65: "Parry",
  66: "ATK Power Rate",
  67: "EXP Rate",
  68: "Jumping",
  69: "Chance Steal HP",
  70: "Chance Bleeding",
  71: "Recovery EXP",
  72: "DEF Rate",
  73: "MP Cost Rate",
  74: "FP Cost Rate",
  75: "Cast Speed Rate",
  76: "Cast Crit Rate",
  77: "Crit Bonus",
  78: "Skill Level",
  79: "Monster DMG",
  80: "PVP DMG",
  81: "Melee Steal HP",
  82: "Heal",
  83: "ATK Power (Flat)",
  85: "One-Hand Mastery",
  86: "Two-Hand Mastery",
  87: "Yo-Yo Mastery",
  88: "Bow Mastery",
  89: "Knuckle Mastery",
  90: "Hawk Eye Rate",
  91: "Resist Magic Rate",
  92: "Gift Box",
  93: "Rest Point Rate",
  94: "Ignore PVP DMG",
  95: "Take PVP Phys DMG Rate",
  96: "Take PVP Magic DMG Rate",
  97: "Take PVE Phys DMG Rate",
  98: "Take PVE Magic DMG Rate",
  99: "Drop All Grade Rate",
  100: "Drop One More",
  101: "PVE Fire DMG Rate",
  102: "PVE Water DMG Rate",
  103: "PVE Elec DMG Rate",
  104: "PVE Wind DMG Rate",
  105: "PVE Earth DMG Rate",
  106: "Equip Level Adj",
  107: "All Skill Level Up",
  108: "DMG vs Stun Rate",
  109: "DMG vs Dark Rate",
  110: "DMG vs Poison Rate",
  111: "DMG vs Slow Rate",
  112: "DMG vs Bleed Rate",
  113: "DMG vs Silent Rate",
  114: "DMG vs Loot Rate",
  115: "DMG vs Stone Rate",
  116: "DMG vs Sleep Rate",

  // Extended range (10000+)
  10000: "Gold",
  10001: "PXP",
  10002: "Resist All",
  10003: "All Stats Up",
  10004: "HP DMG Up",
  10005: "DEF Hit Rate Down",
  10006: "Cure State",
  10007: "HP Recovery Rate",
  10008: "MP Recovery Rate",
  10009: "FP Recovery Rate",
  10010: "Locomotion",
  10011: "All Mastery",
  10012: "All Recovery",
  10013: "All Recovery Rate",
  10014: "Kill All",
  10015: "Kill HP Rate",
  10016: "Kill MP Rate",
  10017: "Kill FP Rate",
  10018: "Kill All Rate",
  10019: "All Cost Rate",
  10020: "Force Max HP DMG",
  10021: "Force Safe HP DMG",
  10022: "Force DMG Value",
  10030: "Heal HP Rate",
  10031: "Heal MP Rate",
  10032: "Heal FP Rate",
  10033: "Heal HP Value",
  10034: "Heal MP Value",
  10035: "Heal FP Value",
  10036: "Debuff All Clear",
};

/** Get a human-readable label for a DST numeric ID. */
export function getDstName(dst: number): string {
  return DST_NAMES[dst] ?? `DST_${dst}`;
}

/**
 * Maps IK2 string symbols to human-readable labels (from defineItemkind.h).
 */
export const IK2_LABELS: Record<string, string> = {
  IK2_NONE: "None",
  IK2_WEAPON_HAND: "Hand Weapon",
  IK2_WEAPON_DIRECT: "Melee Weapon",
  IK2_WEAPON_MAGIC: "Magic Weapon",
  IK2_ARMOR: "Armor",
  IK2_ARMORETC: "Accessory Armor",
  IK2_CLOTH: "Clothing",
  IK2_CLOTHETC: "Accessory Clothing",
  IK2_REFRESHER: "Food (HP)",
  IK2_POTION: "Potion",
  IK2_JEWELRY: "Jewelry",
  IK2_FOOD: "Food",
  IK2_MAGIC: "Magic Item",
  IK2_GEM: "Gem",
  IK2_MATERIAL: "Material",
  IK2_TOOLS: "Tool",
  IK2_SYSTEM: "System",
  IK2_RIDING: "Riding",
  IK2_MOB: "Monster Drop",
  IK2_BLINKWING: "Blinkwing",
  IK2_AIRFUEL: "Air Fuel",
  IK2_CHARM: "Charm",
  IK2_BULLET: "Projectile",
  IK2_TEXT: "Text",
  IK2_GMTEXT: "GM Text",
  IK2_GENERAL: "General",
  IK2_BUFF: "Buff",
  IK2_WARP: "Warp",
  IK2_SKILL: "Skill",
  IK2_CLOTHWIG: "Wig",
  IK2_BUFF2: "Buff (Timed)",
  IK2_FURNITURE: "Furniture",
  IK2_PAPERING: "Wallpaper",
  IK2_TOCASH: "Cash Item",
  IK2_BUFF_TOGIFT: "Buff Gift",
  IK2_GUILDHOUSE_FURNITURE: "Guild Furniture",
  IK2_GUILDHOUSE_NPC: "Guild NPC",
  IK2_GUILDHOUSE_PAPERING: "Guild Wallpaper",
  IK2_GUILDHOUES_COMEBACK: "Guild Recall",
  IK2_KEEP: "Keep",
  IK2_ONCE: "Once",
  IK2_TELEPORTMAP: "Teleport Map",
  IK2_BARUNA: "Baruna",
  IK2_DECREASE: "Decrease Option",
  IK2_RANDOMOPTION: "Random Option",
  IK2_RESET: "Reset Option",
  IK2_COLOSSEUM: "Colosseum",
  IK2_ENCHANT: "Enchant",
  IK2_INCREASE: "Increase Option",
  IK2_UPGRADE: "Upgrade",
  IK2_MAPOPEN: "Map Open",
  IK2_COSTUMESYSTEM: "Costume System",
  IK2_TREASURE: "Treasure",
  IK2_TWOWEAPONMERGE: "Two-Weapon Merge",
  IK2_LEVELDOWNSCROLL: "Level Down Scroll",
  IK2_ELLDINPOTION: "Eldrin Potion",
  IK2_GOLD: "Gold",
  IK2_COUNT: "Count",
};

/**
 * Maps IK3 string symbols to human-readable labels (from defineItemkind.h).
 */
export const IK3_LABELS: Record<string, string> = {
  IK3_NONE: "None",
  IK3_HAND: "Hand",
  IK3_SWD: "Sword",
  IK3_AXE: "Axe",
  IK3_CHEERSTICK: "Cheerstick",
  IK3_KNUCKLEHAMMER: "Knuckle",
  IK3_WAND: "Wand",
  IK3_STAFF: "Staff",
  IK3_THSWD: "Two-Hand Sword",
  IK3_THAXE: "Two-Hand Axe",
  IK3_VIRTUAL: "Virtual",
  IK3_YOYO: "Yo-Yo",
  IK3_BOW: "Bow",
  IK3_YOBO: "Bow (Yo-Yo)",
  IK3_CROSSBOW: "Crossbow",
  IK3_SHIELD: "Shield",
  IK3_HELMET: "Helmet",
  IK3_SUIT: "Suit",
  IK3_GAUNTLET: "Gauntlet",
  IK3_BOOTS: "Boots",
  IK3_HAT: "Hat",
  IK3_MASK: "Mask",
  IK3_SHOES: "Shoes",
  IK3_CLOAK: "Cloak",
  IK3_CLOTH: "Cloth",
  IK3_GLOVE: "Glove",
  IK3_REFRESHER: "HP Food",
  IK3_POTION: "Potion",
  IK3_EARRING: "Earring",
  IK3_NECKLACE: "Necklace",
  IK3_RING: "Ring",
  IK3_INSTANT: "Instant",
  IK3_COOKING: "Cooking",
  IK3_ICECEARM: "Ice Cream",
  IK3_PILL: "Pill",
  IK3_MAGICTRICK: "Magic Trick",
  IK3_GEM: "Gem",
  IK3_DRINK: "Drink",
  IK3_COLLECTER: "Collector",
  IK3_ELECARD: "Element Card",
  IK3_DICE: "Dice",
  IK3_SUPSTONE: "Support Stone",
  IK3_BOARD: "Board",
  IK3_STICK: "Stick",
  IK3_EVENTMAIN: "Event Main",
  IK3_QUEST: "Quest Item",
  IK3_MAP: "Map",
  IK3_BLINKWING: "Blinkwing",
  IK3_EVENTSUB: "Event Sub",
  IK3_TOWNBLINKWING: "Town Blinkwing",
  IK3_CAR: "Car",
  IK3_ACCEL: "Acceleration",
  IK3_DELETE: "Delete",
  IK3_SCROLL: "Scroll",
  IK3_ENCHANTWEAPON: "Enchant Weapon",
  IK3_CFLIGHT: "Flight (C)",
  IK3_BFLIGHT: "Flight (B)",
  IK3_MAGICBOTH: "Magic Both",
  IK3_BCHARM: "Charm (B)",
  IK3_RCHARM: "Charm (R)",
  IK3_ARROW: "Arrow",
  IK3_PIERDICE: "Pierce Dice",
  IK3_SOCKETCARD: "Socket Card",
  IK3_SOCKETCARD2: "Socket Card 2",
  IK3_TEXT_BOOK: "Book",
  IK3_TEXT_SCROLL: "Scroll (Text)",
  IK3_TEXT_LETTER: "Letter",
  IK3_TEXT_UNDYING: "Undying",
  IK3_TEXT_DISGUISE: "Disguise",
  IK3_TEXT_INVISIBLE: "Invisible",
  IK3_TEXT_GM: "GM Text",
  IK3_BINDS: "Binds",
  IK3_CREATE_MONSTER: "Monster Spawn",
  IK3_POTION_BUFF_STR: "STR Potion",
  IK3_POTION_BUFF_DEX: "DEX Potion",
  IK3_POTION_BUFF_INT: "INT Potion",
  IK3_POTION_BUFF_STA: "STA Potion",
  IK3_POTION_BUFF_DEFENSE: "DEF Potion",
  IK3_ANGEL_BUFF: "Angel Buff",
  IK3_PET: "Pet",
  IK3_RANDOM_SCROLL: "Random Scroll",
  IK3_ULTIMATE: "Ultimate",
  IK3_LINK: "Link",
  IK3_GENERAL: "General",
  IK3_ENCHANT: "Enchant",
  IK3_EGG: "Egg",
  IK3_FEED: "Feed",
  IK3_TICKET: "Ticket",
  IK3_POCKET: "Pocket",
  IK3_BED: "Bed",
  IK3_SOFA: "Sofa",
  IK3_WARDROBE: "Wardrobe",
  IK3_CLOSET: "Closet",
  IK3_TABLE: "Table",
  IK3_CABINET: "Cabinet",
  IK3_PROPS: "Props",
  IK3_WALLPAPER: "Wallpaper",
  IK3_CARPET: "Carpet",
  IK3_COUPLE_BUFF: "Couple Buff",
  IK3_FUNNYCOIN: "Funny Coin",
  IK3_FLOWER: "Flower",
  IK3_BALLOON: "Balloon",
  IK3_WING: "Wing",
  IK3_VIS: "Vis",
  IK3_TS_BUFF: "TS Buff",
  IK3_TELEPORTER: "Teleporter",
  IK3_REST: "Rest",
  IK3_DESK: "Desk",
  IK3_CHAIR: "Chair",
  IK3_CASE: "Case",
  IK3_BATH: "Bath",
  IK3_DRAWER: "Drawer",
  IK3_CRYSTAL: "Crystal",
  IK3_KEY: "Key",
  IK3_CROSSARROW: "Cross Arrow",
  IK3_MAGICBARUNA: "Magic Baruna",
  IK3_ZEMBARUNA: "Zem Baruna",
  IK3_SHILDBARUNA: "Shield Baruna",
  IK3_SUMMON_NPC: "Summon NPC",
  IK3_OPERCID: "Opercid",
  IK3_OPER: "Oper",
  IK3_CID: "Cid",
  IK3_OPERCRYSTAL: "Oper Crystal",
  IK3_CIDCRYSTAL: "Cid Crystal",
  IK3_OPERMIX: "Oper Mix",
  IK3_CIDMIX: "Cid Mix",
  IK3_MEAL: "Meal",
  IK3_EXTRACT: "Extract",
  IK3_BARUNA: "Baruna",
  IK3_EXP_RATE: "EXP Rate",
  IK3_GENERAL_ENCHANT_RATE: "Enchant Rate",
  IK3_GEN_ATT_ENCHANT_RATE: "Atk Enchant Rate",
  IK3_GENERAL_WEAPON_ENCHANT_RATE: "Weapon Enchant Rate",
  IK3_ULTIMATE_UPGRADE_RATE: "Ultimate Upgrade Rate",
  IK3_RESET_BIND: "Reset Bind",
  IK3_BARUNA_PROTECTION: "Baruna Protection",
  IK3_BARUNA_PROTECTION_KEEP: "Baruna Protection Keep",
  IK3_BARUNAWEA_PIERCE_RUNE: "Baruna Weapon Pierce",
  IK3_BARUNAAMO_PIERCE_RUNE: "Baruna Armor Pierce",
  IK3_BARUNA_PROTECTION_RUNE: "Baruna Protection Rune",
  IK3_BARUNA_PIERCE_RATE: "Baruna Pierce Rate",
  IK3_COLOSSEUM_BOSS_RATE: "Colosseum Boss Rate",
  IK3_COLOSSEUM_RETRY: "Colosseum Retry",
  IK3_COSTUME_DEFENDER: "Costume Defender",
  IK3_MAPOPEN_AREA: "Map Open Area",
  IK3_MAPOPEN_DUNGEON: "Map Open Dungeon",
  IK3_TELEPORTMAP_BASIC: "Teleport Map (Basic)",
  IK3_TELEPORTMAP_USER: "Teleport Map (User)",
  IK3_GOLD: "Gold",
  IK3_USESKILL: "Use Skill",
};

/** Label for IK2 symbol, falling back to the raw symbol. */
export function getIk2Label(sym: string): string {
  return IK2_LABELS[sym] ?? sym.replace(/^IK2_/, "").replace(/_/g, " ");
}

/** Label for IK3 symbol, falling back to the raw symbol. */
export function getIk3Label(sym: string): string {
  return IK3_LABELS[sym] ?? sym.replace(/^IK3_/, "").replace(/_/g, " ");
}
